[package]
name = "pmbus"
version = "0.1.0"
authors = ["Bryan Cantrill <bryan@oxide.computer>"]
edition = "2018"

[dependencies]
num-traits = { version = "0.2.12", default-features = false }
num-derive = "0.3"
libm = "0.2.1"
